# Must define the following environment variables in CircleCI web interface:
#  * TWINE_USERNAME
#  * TWINE_PASSWORD


version: 2.1


executors:
  python:
    parameters:
      version:
        type: string
        default: "2.7"
    docker:
      - image: circleci/python:<< parameters.version >>
    working_directory: ~/repo


commands:
  build:
    steps:
      - checkout
      - restore_cache:
          key: juriscraper-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
      - run:
          name: Install Dependencies
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            pip install -r requirements.txt -r requirements-dev.txt
      - save_cache:
          key: juriscraper-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
          paths:
            - venv

  test:
    steps:
      - run:
          name: Run the Test Suite
          command: |
            . venv/bin/activate
            python setup.py test
            
  test-network:
    steps:
      - run:
          name: Run the Network Test Suite (these tests don't run by default)
          command: |
            . venv/bin/activate
            python -m unittest discover -s tests/network -v
            
jobs:
  build:
    executor: python
    steps:
      - build

  2.7-build-test:
    executor: python
    <<: &build-test
      steps:
        - build
        - test

  2.7-build-test-network:
    executor: python
    <<: &build-test-network
      steps:
        - build
        - test-network

  3.5-build-test:
    <<: *build-test
    <<: &3.5
      executor: python
        version: "3.5"

  3.5-build-test-network:
    <<: *build-test-network
    <<: *3.5

  3.6-build-test:
    <<: *build-test
    <<: &3.6
      executor: python
        version: "3.6"

  3.6-build-test-network:
    <<: *build-test-network
    <<: *3.5

  deploy:
    executor: python
    steps:
      - build
      - run:
          name: Deploying release package to PyPI
          command: |
            . venv/bin/activate
            echo "{ Verify Git Tag Matches setup.py VERSION }"
            python setup.py verify
            echo "{ Creating Release Packages }"
            python setup.py sdist bdist_wheel
            echo "{ Uploading Release Packages to PyPI }"
            twine upload dist/*
workflows:
  version: 2

  untagged:
    jobs:
      - build
      - 2.7-build-test: &require-build
          requires:
            - build
      - 2.7-build-test-network: *require-build
      - 3.5-build-test: *require-build
      - 3.5-build-test-network: *require-build
      - 3.6-build-test: *require-build
      - 3.6-build-test-network: *require-build

  # For tagged releases, run all tests across all version, but don't
  # *require* network tests to pass in order to publish release
  tagged:
    jobs:
      - build: &filter-tags
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - 2.7-build-test: &filter-tags-and-require-build
          <<: *filter-tags
          <<: *require-build
      - 2.7-build-test-network: *filter-tags
      - 3.5-build-test: *filter-tags-and-require-build
      - 3.5-build-test-network: *filter-tags
      - 3.6-build-test: *filter-tags-and-require-build
      - 3.6-build-test-network: *filter-tags-and-require-build
      - deploy:
          <<: *filter-tags
          requires:
            - build-test-2.7
            - build-test-3.5
            - build-test-3.6
